name: Run Diameter of Binary Tree Tests

on:
  push:
    paths:
      - 'solutions/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'solutions/**'
      - 'tests/**'

jobs:
  check-solution-count:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.get_language.outputs.language }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch full Git history (needed for HEAD~1)
        run: git fetch --prune --unshallow || true

      - name: Count Modified Solution Files
        id: get_language
        shell: bash
        run: |
          # Determine base commit depending on event type
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base_commit="origin/${{ github.base_ref }}"
          else
            base_commit="HEAD~1"
          fi

          echo "Comparing changes between $base_commit and HEAD"
          changed_files=$(git diff --name-only "$base_commit" HEAD | grep '^solutions/' || true)
          echo "Changed files: $changed_files"

          count=$(echo "$changed_files" | wc -l)

          if [ "$count" -gt 1 ]; then
            echo "::error ::Multiple Solution codes Changed at a time and do not Run Tests"
            exit 1
          fi

          if echo "$changed_files" | grep -q 'base'; then
            echo "::error ::Base code detected. Aborting."
            exit 1
          fi

          if echo "$changed_files" | grep -q '\.c$'; then
            echo "language=c" >> "$GITHUB_OUTPUT"
          elif echo "$changed_files" | grep -q '\.cpp$'; then
            echo "language=cpp" >> "$GITHUB_OUTPUT"
          elif echo "$changed_files" | grep -q '\.py$'; then
            echo "language=python" >> "$GITHUB_OUTPUT"
          elif echo "$changed_files" | grep -q '\.java$'; then
            echo "language=java" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::No known language changed."
            exit 1
          fi  # ← MISSING fi added here

  test:
    needs: check-solution-count
    runs-on: ubuntu-latest
    if: ${{ needs.check-solution-count.outputs.language != '' }}
    steps:
      - uses: actions/checkout@v3

      - name: Run C Test
        if: ${{ needs.check-solution-count.outputs.language == 'c' }}
        run: |
          sudo apt update && sudo apt install -y gcc
          gcc tests/diameter_of_binary_tree_test.c solutions/diameter_of_binary_tree.c -o c_test
          ./c_test

      - name: Run C++ Test
        if: ${{ needs.check-solution-count.outputs.language == 'cpp' }}
        run: |
          sudo apt update && sudo apt install -y g++
          g++ tests/diameter_of_binary_tree_test.cpp solutions/diameter_of_binary_tree.cpp -o cpp_test
          ./cpp_test

      - name: Run Python Test
        if: ${{ needs.check-solution-count.outputs.language == 'python' }}
        run: |
          python3 tests/diameter_of_binary_tree_test.py

      - name: Run Java Test
        if: ${{ needs.check-solution-count.outputs.language == 'java' }}
        run: |
          javac solutions/Solution.java tests/Test.java
          java -cp solutions:tests Test
